[package]
name = "journal"
version = "0.1.0"
authors = ["Stephen Hunt <stphnhnt.git@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
dirs-next = "2.0"
log = "0.4"
itertools = "0.10"
once_cell = "1.5"
pretty_env_logger = "0.4"
ring = "0.16"
rpassword = "5.0"
rusqlite = { version = "0.24", features = ["chrono"] }
serde = { version = "1", features = ["derive"] }
structopt = "0.3"
tempfile = "3.2"
toml = "0.5"
